version: '3.8'

services:
  # Aplicação principal
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
      - MONGODB_URI=mongodb://mongo:27017/login-app
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  # Banco de dados MongoDB
  mongo:
    image: mongo:6.0
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=login-app
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

  # MongoDB Express (interface web opcional)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "5000:5000"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge 